version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Setup CF CLI
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
  unit_tests:
    docker:
      - image: circleci/openjdk:8-jdk
      working_directory: ~/repo
      environment:
        JVM_OPTS: -Xmx3200m
        TERM: dumb
      steps:
        - checkout
        - run: ./gradlew build
  deply:
    docker:
      - image: circleci/openjdk:8-jdk
      working_directory: ~/repo
      environment:
        JVM_OPTS: -Xmx3200m
        TERM: dumb
      steps:
        - run: cf login -a https://donotuseapi.run.pivotal.io -u "$CF_USER" -p "$CF_PASSWORD"
        - run: cf push guild
  workflows:
    version: 2
      jobs:
        - dependencies
        - unit_tests:
          requires:
          - dependencies
        - deploy:
            requires:
              - unit_tests
