version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
            - gradle-cache-
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-{{ checksum "build.gradle" }}
  unit_tests:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ./gradlew build
      - save_cache:
          paths:
            - build/libs
          key: jar-cache-{{ checksum "guild-interview-0.0.1-SNAPSHOT.jar" }}
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - jar-cache-{{ checksum "guild-interview-0.0.1-SNAPSHOT.jar" }}
            - jar-cache-
      - run:
          name: Setup CF CLI & Deploy
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf login -a https://donotuseapi.run.pivotal.io -u "$CF_USER" -p "$CF_PASSWORD"
            cf push guild -p build/libs/guild-interview-0.0.1-SNAPSHOT.jar
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - dependencies
      - unit_tests:
          requires:
          - dependencies
      - deploy:
          requires:
            - unit_tests
